version: '3'


services:

  redis-1:
    container_name: redis-1
    build: redis-1
    command: redis-server /etc/redis/redis.conf
    network_mode: "host"


  redis-2:
    container_name: redis-2
    build: redis-2
    command: redis-server /etc/redis/redis.conf
    depends_on:
      - redis-1
    network_mode: "host"


  # redis-3:
  #   container_name: redis-3
  #   build: redis-3
  #   command: redis-server /etc/redis/redis.conf
  #   depends_on:
  #     - redis-2
  #   network_mode: "host"


  # redis-4:
  #   container_name: redis-4
  #   build: redis-4
  #   command: redis-server /etc/redis/redis.conf
  #   depends_on:
  #     - redis-3
  #   network_mode: "host"


  # redis-5:
  #   container_name: redis-5
  #   build: redis-5
  #   command: redis-server /etc/redis/redis.conf
  #   depends_on:
  #     - redis-4
  #   network_mode: "host"


  # redis-6:
  #   container_name: redis-6
  #   build: redis-6
  #   command: redis-server /etc/redis/redis.conf
  #   depends_on:
  #     - redis-5
  #   network_mode: "host"



