version: '3'


services:

  redis-1:
    container_name: redis-1
    build: redis-1
    restart: always
    command: redis-server /etc/redis/redis.conf
    volumes:
            - /mnt/docker/redis1:/data
    network_mode: "host"
  
  redis-2:
    container_name: redis-2
    build: redis-2
    restart: always
    command: redis-server /etc/redis/redis.conf
    volumes:
          - /mnt/docker/redis2:/data
    network_mode: "host"


  



