version: '3'


services:

  redis-1:
    container_name: redis-1
    build: redis-1
    command: redis-server /etc/redis/redis.conf
    network_mode: "host"


  healthcheck:
    container_name: healthcheck
    image: "chetandev/redis-health-check"
    environment:
       - REDIS_PORT=6379
       - REDIS_HOST=redis-1
       - PORT=80
    network_mode: "host"



  



