version: '3'


services:

  redis-1:
    container_name: redis-1
    build: redis-1
    command: redis-server /etc/redis/redis.conf
    network_mode: "host"


  healthcheck:
    image: "chetandev/redis-health-check"
    network_mode: "host"
    


  



